FULL_UPDATE_PREFIX = 'VIMPAIR_FULL_UPDATE'
UPDATE_START_PREFIX = 'VIMPAIR_CONTENTS_START'
UPDATE_PART_PREFIX = 'VIMPAIR_CONTENTS_PART'
UPDATE_END_PREFIX = 'VIMPAIR_CONTENTS_END'
CURSOR_POSITION_PREFIX = 'VIMPAIR_CURSOR_POSITION'
TAKE_CONTROL_MESSAGE = 'VIMPAIR_TAKE_CONTROL'
FILE_CHANGE_PREFIX = 'VIMPAIR_FILE_CHANGE'
SAVE_FILE_MESSAGE = 'VIMPAIR_SAVE_FILE'

MESSAGE_LENGTH = 1024
